openapi: 3.0.1
info:
  title: potholes-rest
  description: API Definition of potholes-rest
  version: v1
servers:
- url: http://localhost:8290/default
paths:
  /api/potholes:
    get:
      responses:
        default:
          description: Default response
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
    options:
      responses:
        default:
          description: Default response
  /api/potholes/{pothole_id}:
    get:
      parameters:
      - name: pothole_id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
    put:
      parameters:
      - name: pothole_id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
    delete:
      parameters:
      - name: pothole_id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
    options:
      parameters:
      - name: pothole_id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
  /api/users:
    get:
      responses:
        default:
          description: Default response
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
    options:
      responses:
        default:
          description: Default response
  /api/users/{user_id}:
    get:
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
    put:
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
    delete:
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
    options:
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
